package com.Arjunagi.DoctorApp.models.doctorRecord;

public enum MedicalSpecialization {
    CARDIOLOGY,
    DERMATOLOGY,
    ENDOCRINOLOGY,
    GASTROENTEROLOGY,
    HEMATOLOGY,
    INFECTIOUS_DISEASE,
    NEUROLOGY,
    ONCOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    OTOLARYNGOLOGY,
    PEDIATRICS,
    PSYCHIATRY,
    PULMONOLOGY,
    RADIOLOGY,
    RHEUMATOLOGY,
    UROLOGY,
    GYNECOLOGY,
    NEPHROLOGY,
    PATHOLOGY,
    CARDIOTHORACIC_SURGERY,
    PLASTIC_SURGERY,
    VASCULAR_SURGERY,
    DENTISTRY,
    OTHER;
}

